# Generated by Django 5.0.6 on 2024-06-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2555)),
                ('domain', models.CharField(max_length=2555)),
                ('year_founded', models.IntegerField()),
                ('industry', models.CharField(max_length=2555)),
                ('size_range', models.CharField(max_length=1005)),
                ('locality', models.CharField(max_length=2555)),
                ('country', models.CharField(max_length=1005)),
                ('linkedin_url', models.URLField()),
                ('current_employee_estimate', models.IntegerField()),
                ('total_employee_estimate', models.IntegerField()),
            ],
        ),
    ]
