# Generated by Django 5.0.6 on 2024-06-09 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YourModel',
            new_name='data',
        ),
    ]
