# Generated by Django 5.0.6 on 2024-06-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='hello',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
