# Generated by Django 5.0.6 on 2024-06-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_data', '0002_rename_yourmodel_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
