# Generated by Django 5.0.6 on 2024-06-11 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_data', '0002_data_hello'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='hello',
        ),
    ]
