# Generated by Django 5.0.6 on 2024-06-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_data', '0003_alter_data_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
