# Generated by Django 5.0.6 on 2024-06-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_data', '0005_alter_data_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='unknown_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
