# Generated by Django 5.0.6 on 2024-06-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_data', '0006_data_unknown_id_alter_data_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
